services:
  subscription-db:
    image: postgres:15
    container_name: subscription-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5430:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  subscription-app:
    build: .
    container_name: subscription
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - '3000:3000'
    depends_on:
      - subscription-db

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
