version: '3.9'

services:
  app:
    container_name: subscription
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: subscription-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password # ⚠️ 실제 비밀번호로 교체
      POSTGRES_DB: subscription
    ports:
      - '5430:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
